schema_version: 1

context:
  name: wadler-lindig
  version: "0.1.5"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/wadler_lindig-${{ version }}.tar.gz
  sha256: c8d6c0e74fc61c7108077009238b7f5a5a52b25f75e024dac313393faf7f7440

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}


tests:
  - python:
      python_version: ${{ python_min }}
      pip_check: true
      imports:
        - wadler_lindig

about:
  homepage: https://github.com/patrick-kidger/wadler_lindig
  summary: A Wadler–Lindig pretty-printer for Python.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dhirschfeld
